In [1]:
import numpy as np

In [12]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[2]

2

In [6]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[2:4]

array([2, 3])

In [8]:
arr[arr > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr_2d = np.random.randn(3, 5)
arr_2d

array([[ 0.36812062,  1.42793439, -0.49053697,  0.50473835, -1.11699961],
       [ 1.63018043,  0.12382579,  0.27830096, -0.21448823, -2.0880493 ],
       [ 1.75025035,  0.97091148,  1.77950232,  1.35881185, -1.31957145]])

In [14]:
arr_2d[:2, 2:]

array([[-0.49053697,  0.50473835, -1.11699961],
       [ 0.27830096, -0.21448823, -2.0880493 ]])

In [15]:
arr_2d[arr_2d >= 0]

array([0.36812062, 1.42793439, 0.50473835, 1.63018043, 0.12382579,
       0.27830096, 1.75025035, 0.97091148, 1.77950232, 1.35881185])

In [22]:
b = arr_2d[0, 0]
b = 0
arr_2d[0, 0], b

(0.3681206197628829, 0)

In [25]:
c = arr_2d[0]
c = [0, 0, 0, 0, 0]
arr_2d[0], c

(array([ 0.36812062,  1.42793439, -0.49053697,  0.50473835, -1.11699961]),
 [0, 0, 0, 0, 0])

In [28]:
arr_2d[0] = [0, 0, 0, 0, 0]
arr_2d

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.63018043,  0.12382579,  0.27830096, -0.21448823, -2.0880493 ],
       [ 1.75025035,  0.97091148,  1.77950232,  1.35881185, -1.31957145]])

In [29]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [31]:
arr_2d[(3, 1), 1:4]

array([[31, 32, 33],
       [11, 12, 13]])