# Numpy Tutorial

In [1]:
import numpy as np

In [6]:
print([1, 2, 3])
np.array([1, 2, 3])

[1, 2, 3]


array([1, 2, 3])

In [7]:
print([[1, 2, 3], [4, 5, 6]])
np.array([[1, 2, 3], [4, 5, 6]])

[[1, 2, 3], [4, 5, 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2, 3))
np.zeros((2, 2, 1))

array([[[0.],
        [0.]],

       [[0.],
        [0.]]])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.linspace(10, 20, 11)


array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [23]:
np.linspace(10, 20, 100)

array([10.        , 10.1010101 , 10.2020202 , 10.3030303 , 10.4040404 ,
       10.50505051, 10.60606061, 10.70707071, 10.80808081, 10.90909091,
       11.01010101, 11.11111111, 11.21212121, 11.31313131, 11.41414141,
       11.51515152, 11.61616162, 11.71717172, 11.81818182, 11.91919192,
       12.02020202, 12.12121212, 12.22222222, 12.32323232, 12.42424242,
       12.52525253, 12.62626263, 12.72727273, 12.82828283, 12.92929293,
       13.03030303, 13.13131313, 13.23232323, 13.33333333, 13.43434343,
       13.53535354, 13.63636364, 13.73737374, 13.83838384, 13.93939394,
       14.04040404, 14.14141414, 14.24242424, 14.34343434, 14.44444444,
       14.54545455, 14.64646465, 14.74747475, 14.84848485, 14.94949495,
       15.05050505, 15.15151515, 15.25252525, 15.35353535, 15.45454545,
       15.55555556, 15.65656566, 15.75757576, 15.85858586, 15.95959596,
       16.06060606, 16.16161616, 16.26262626, 16.36363636, 16.46464646,
       16.56565657, 16.66666667, 16.76767677, 16.86868687, 16.96

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.rand(2, 3)

array([[0.06136045, 0.9489976 , 0.47852287],
       [0.84967038, 0.06651704, 0.43281582]])

In [36]:
N = 10000000
a = np.random.randn(N)
sum(a)/N

-0.00021048021132260178

In [32]:
a = [1, 2]
a

[1, 2]

In [38]:
np.random.randint(1, 100, 20)

array([94, 76, 51, 32, 39, 23,  1, 38, 30, 41,  1, 11, 80, 57, 87, 29,  1,
       81, 77, 27])

In [43]:
arr = np.arange(20)
ranarr = np.random.randint(0, 50, 10)

In [44]:
arr.reshape(10, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [45]:
ranarr

array([20, 10, 10, 30, 25, 44, 23, 42, 18, 26])

In [46]:
ranarr.max()

44

In [47]:
ranarr.min()

10

In [49]:
max_i = ranarr.argmax()
max_i

5

In [50]:
ranarr.max() == ranarr[max_i]

True

In [52]:
arr.shape

(20,)

In [55]:
arr = arr.reshape(2, 10)
arr.shape

(2, 10)

In [56]:
arr.dtype

dtype('int32')